apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-microservice
  labels:
    app: api-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-microservice
  template: #va lo que le vamos a poner a cada pod
    metadata:
      labels:
        app: api-microservice
    spec:
      containers:
        - name: api-microservice
          image: nestorx211/k8s-microservice-python:1.0.0
          ports:
            - containerPort: 8000
