apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-microservice
  labels:
    app: api-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-microservice
  template:
    metadata:
      labels:
        app: api-microservice
    spec:
      containers:
        - name: api-microservice
          image: nestorx211/k8s-microservice-python:1.0.0
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 6000m
              memory: 1Gi
