image:
  repository: nestorx211/api-microservice
  tag: prod-6fdb8b5f686b04d92f464464e157b312b3797f66
  pullPolicy: Always
env: prod
replicaCount: 2
resources:
  requests:
    cpu: 200m
    memory: 500Mi
  limits:
    cpu: 600m
    memory: 1Gi
hpa:
  minReplicas: 2
  maxReplicas: 4
  cpuUtilization: 70
ingress:
  path: /prod/users(/|$)(.*)
