image:
  repository: nestorx211/api-microservice
  tag: dev-83ef6cdba9e39df7e66848f8410c6c716160f3c2
  pullPolicy: Always
env: dev
replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi
hpa:
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 70
ingress:
  path: /dev/users(/|$)(.*)
