image:
  repository: nestorx211/api-microservice
  tag: dev-997813de2435852ccb401740efff1f4e2a8e47d2
  pullPolicy: Always
env: dev
replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi
hpa:
  minReplicas: 1
  maxReplicas: 2
  cpuUtilization: 70
ingress:
  path: /dev/users(/|$)(.*)
