image:
  repository: nestorx211/api-microservice
  tag: dev-0978c8237e59d8ba2600498d10f8dfb9c31fe05a
  pullPolicy: Always
env: dev
replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi
hpa:
  minReplicas: 1
  maxReplicas: 2
  cpuUtilization: 70
ingress:
  path: /dev/users(/|$)(.*)
